services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns 
    ports:
      - "53:53/udp"

  web1:
    build:
      context: ./web1
      dockerfile: Dockerfile
    container_name: web1


  web2:
    build:
      context: ./web2
      dockerfile: Dockerfile
    container_name: web2 


  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"